# Site settings
title: jeongmyeong zZZ
description: >
  dotmyeom.me
author: jeongmyeong
email: kimbym23@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jeongmyeongzZ.github.io" # the base hostname & protocol for your site
facebook_username: 100017805346667
linkedin_username: 정명-김-5549721b4
github_username:  jeongmyeongzZ

disqus_shortname: dotmyeom.me

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed

gems:
  - jemoji
  - jekyll-sitemap
# - amp-jekyll # Acceletrated Mobile Pages

# AMP Settings
# ampdir: amp/
# enable_amp: true

# Google Analytics
# google_analytics: UA-XXXXXXXX-X
